### PR TITLE
Add more missing files including the old Libs folder

### PR DESCRIPTION
**Pull request by gbowne1**
This PR 

- [x] adds back the old Libs folder
- [x] adds the missing code from header.php
- [x] removes deprecated VSCode extensions from the .vscode folder
- [x] minor fixes to launch.json
- [x] Adds proper settings.json for web development including language specific settings

There are well over 1k files in this PR because of the Libs folder, so no need to review that.  

We still need to test and configure Visual Studio 2019 ~ 2022 for this project.  Anyone have VS?

It also needs a IntelliJ, Atom and PHPStorm config folder, although I may have the original .idea folder from when @idormain was working on it.

### CODE REVIEW

**Comment by gbowne1** [comment]
This would at least resolve Issue #28

**Comment by hitblast** [comment]
LGTM!

**Comment by gbowne1** [comment]
This has security vulnerabilities.  The jQWidgets and Toastr libraries in /Libs both need re-downloaded and updated.. if indeed these were fixed in new versions.

I feel like we should be using Bootstrap 5.2 which has built in Toasts, PopperJS for poppers and jQueryUI for UI stuff.  

I still feel like there are missing files.. but yeah, this *should* be the last of the missing files.  I was just going through the stuff I downloaded from the orig repository before migrating to Org and found a few that reference files that are here already.

**Comment by gbowne1** [comment]
I think I may have found the correct header.php

I will add it in the next PR.

**Comment by hitblast** [comment]
Alright, seems reasonable. Also how about using Tailwind instead of Bootstrap?

**Comment by gbowne1** [comment]
I'm focused on getting back to where we were last when he was working on it.

With Bootstrap 5.2 it comes a lot of nice things. 

Theres other CDN libraries I commented out we can look at.  Modenizr, MaterialUI/Material.io, etc.

**Comment by idormain** [comment]
Hiya Greg

You should no longer use the JQWidgets library as they are personally licensed to me and I’ll need to use them in an upcoming project. 

Cancer sucks going to chemo from the 30th September. Still feeling very tired. Fuego now has two way SMS with SMS history bound to Jobs and Quotes. 

Hope you’re well!

Talk again sorry on

Kind regards 

Ivan

**Comment by gbowne1** [comment]
@idormain 

I am going to be probably redoing tgis site  anyways, if not to change the libraries it uses and remove the old ones because Toasts are built into Bootstrap 5 and I have found jQuery UI a lot better to use.. 

I would suggest to you if youre using Toasts for notifications etc to use Bootstrap.  I would also suggest using any UI library other than jQWidgets.

I may even suggest Materialize.

I still need to get time to remove all the jQWidgets stuff from the actual site code. Some stuff wont work if I remove the library files 

There is a jQWidgets and Toastr CDN as well but I cant tell whether the new versions have removed the security vulnerabilities..  another reason you or anyone else should not use it.  Particularly because of the log4j security issues it has.

Is the radio logger server you created still running?  

Cheers

**Pull request merged**
